from django.urls import path
from . import views
from .views import UpdateCartView

urlpatterns = [
    path(
        'product-chapters-list/',
        views.ProductChapterListView.as_view(),
        name='product-chapters-list'
    ),
    path(
        'product-categories-list/',
        views.ProductCategoryListView.as_view(),
        name='product-categories-list'
    ),
    path(
        'brands-list/',
        views.BrandListView.as_view(),
        name='brand-list'
    ),
    path(
        'countries-list/',
        views.CountryListView.as_view(),
        name='country-list'
    ),
    path(
        'products-list/',
        views.ProductListView.as_view(),
        name='product-list'
    ),
    path(
        'products/<int:pk>/',
        views.ProductDetailView.as_view(),
        name='product-detail'
    ),
    path(
        'cart/',
        views.CartDetailView.as_view(),
        name='cart-detail'
    ),
    path(
        'cart/add/',
        views.AddToCartView.as_view(),
        name='add-to-cart'
    ),
    path(
        'cart/remove/<int:product_variant_id>/',
        views.RemoveFromCartView.as_view(),
        name='remove-from-cart'
    ),
    path(
        'cart/update/<int:product_variant_id>/',
        UpdateCartView.as_view(),
        name='update-cart-item'
    ),
    path(
        'orders/create/',
        views.OrderCreateView.as_view(),
        name='order-create'
    ),
    path(
        'orders/',
        views.OrderListView.as_view(),
        name='order-list'
    ),
    path(
        'orders/<int:pk>/status/',
        views.OrderStatusUpdateView.as_view(),
        name='order-status-update'
    ),
    path(
        'favorites/',
        views.FavoriteProductListView.as_view(),
        name='favorite-list'
    ),
    path(
        'favorites/add/',
        views.FavoriteProductCreateView.as_view(),
        name='favorite-add'
    ),
    path(
        'favorites/remove/<int:product_id>/',
        views.FavoriteProductDeleteView.as_view(),
        name='favorite-remove'
    ),
    path(
        'favorites/clear/',
        views.FavoriteProductClearView.as_view(),
        name='favorite-clear'
    ),
    path(
        'products/<int:product_id>/reviews/',
        views.ReviewListView.as_view(),
        name='review-list'
    ),
    path(
        'products/<int:product_id>/reviews/create/',
        views.ReviewCreateView.as_view(),
        name='review-create'
    ),
    path(
        'products/<int:product_id>/reviews/<int:pk>/',
        views.ReviewDeleteView.as_view(),
        name='review-delete'
    ),
]
